trigger:
- master

pool:
  name: 'agent1'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  outputDirectory: '$(Build.ArtifactStagingDirectory)/WebApplication1'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 8.0 SDK'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(solution)'

- script: |
    echo "Cleaning output directory..."
    if [ -d "$(outputDirectory)" ]; then
      rm -rf $(outputDirectory)
      echo "Output directory cleaned."
    else
      echo "Output directory does not exist, creating it..."
    fi
    mkdir -p $(outputDirectory)
    echo "Output directory created."
  displayName: 'Clean and Create Output Directory'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) --output $(outputDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(outputDirectory)'
    ArtifactName: 'drop'
